### ISSUE TITLE
Pick up HTML encodings from meta tags?

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#5] opened 2022-11-23 12:51 UTC
This page uses `ksc-5601` South Korean encoding as described in the meta tag of the HTML page.

- http://discmaster.textfiles.com/view/4411/DOKAN13.iso/Webs/www.gainax.co.jp/akiba-k.html

Maybe these meta tags can be parsed for encodings? Might be a quick win for correcting the encoding of various exotic HTML.

**Comment by Sembiance** [comment] 2022-11-23 16:54
Viewing the file directly works: http://discmaster.textfiles.com/file/4411/DOKAN13.iso/Webs/www.gainax.co.jp/akiba-k.html

This is because discmaster doesn't specify a charset header in the HTTP response of individual files, allowing the browser to determine the charset. Thus when viewed directly, the browser correctly sees the `<META HTTP-EQUIV="Content-Type" CONTENT="text/html;CHARSET=ksc-5601">` line in the HTML file and renders it in South Korean.

The problem is the parent 'view' page is in `UTF-8` encoding and the HTML file is delivered in an `<iframe>`.
You would imagine that an `<iframe>` would render the file the same way as viewing it directly, detect the `<META HTTP-EQUIV` tag and render the characters properly.

Sadly this doesn't seem to be happening. Some research shows that different charset encoding within iframes may only work if the HTTP server itself sends the proper charset header for the file in the iframe. That won't be easy for discmaster to do, due to the way it's designed.

A workaround would be to pre-parse all HTML files and for any that specify a charset in their HTML, pre-convert them from that chartset into UTF-8 and modify the HTML to specifcy that it's now UTF-8 encoded. That's basically how Mac Japanese HTML files are handled.

I'll think on it some more.

**Comment by gingerbeardman** [comment] 2022-11-23 18:47
Interesting, viewing the file directly on iOS (which is where I spotted it) and macOS (where the screenshot below is from) it appears garbled and "not decoded" if that's the correct way to phrase it?

![Screen shot 2022-11-23 at 18 45 47](https://user-images.githubusercontent.com/49612/203624565-1786851e-cf2d-491c-990c-4ff078cab7fc.png)

**Comment by Sembiance** [comment] 2022-11-23 18:56
That is interesting! It looks a lot nicer under Linux with Brave browser (chromium based):
![screenshot_2022-11-23_13:54:06](https://user-images.githubusercontent.com/81436/203625940-be60a497-dc04-4b53-80d0-ba9762f616ec.png)

But copying those characters into Google translate it comes up as Japanese and not Korean, so maybe the browser is getting it wrong here.

Sounds like doing the character converting myself, based on what the stated charset is, sounds like the best approach.

**Comment by Sembiance** [comment] 2022-11-23 23:49
> I do think there are a couple of things at play:
> 1. the meta tag thing you are thinking on
> 2. charsets that are not supported by modern browsers (i never would have thought this would happen!)

If I pre-convert files to UTF, I can take care of both of these issues, so that's the plan :)

**Comment by Sembiance** [comment] 2024-04-12 17:54
discmaster2 detects declared HTML charsets/encodings from meta tags and handles them correctly when converting to UTF-8.

**discmaster1**
![before](https://github.com/Sembiance/dexvert/assets/81436/61e145a6-da38-4938-b003-23c75b0685fd)

**discmaster2**
![after](https://github.com/Sembiance/dexvert/assets/81436/3f27f60e-7513-4fff-a491-04979e2faa6b)

Also in discmaster2 clicking the download link will download the original un-modified HTML file (discmaster1 pre-mangled the HTML, losing the original).

<hr>

However for this specific encoding,  `KSC-5601`, I have failed to get it to convert. As you discovered, `KSC-5601` does not appear to be properly supported by modern browsers, even viewing the file directly doesn't look quite right. Perhaps a browser installed on a South Korean locale system may have better luck, perhaps not.

discmaster2 uses `iconv` from `glibc` to convert encodings/charsets, but it doesn't have `KSC-5601` as an option (`iconv --list`). It's code has a `ksc5601.c` file and some other encodings use it, but attempting to convert withsome of the ones I tried just yielded gibberish.

I also tried using `libiconv` which is different from the `glibc` version and it's tool lists `KSC-5601` as an option, but attempts to use it to convert the text also failed.

I tried some other tools as well such as `recode` and `nkf` but neither worked.

So for this particular charset, I don't know of any linux based too that can convert it to UTF-8 so there isn't much I can do with it. 

Thus I'm gonna go ahead and close this issue out, since discmaster2 does not properly handle meta declared HTML encodings, just not `KSC-5601`. Maybe some day I'll discover a tool that can convert it.

**Closed by Sembiance** 2024-04-12 17:54 UTC
Labels: enhancement

**Comment by gingerbeardman** [comment] 2024-04-12 19:34
Today is the day!

The tool is Tcl, which has support for KSC-5601 (and many more).

Generally Tcl has great support for text encoding conversion, a lot of it written by Apple back in the early 1990s when they had to deal with dozens of text encoding. Long before UTF was even a twinkle in the eye.

I use Tcl to convert old the mish-mash Macintosh of encodings present in the file listings of my CD-ROM collection: https://www.gingerbeardman.com/mmm/ as detailed here: https://blog.gingerbeardman.com/2022/03/31/working-with-classic-macintosh-text-encodings-in-the-age-of-unicode/#convert2unicode

Here's my conversion script (defaults to `MacJapan` for my own purposes), so run it like `./convert2unicode.tcl -encoding ksc5601 akiba-k.html` but I'm unsure of the exact set of conversion steps to get the correct output.

https://gist.github.com/gingerbeardman/4a3b66236e018b72b32ca17953474e12#file-convert2unicode-tcl

**Comment by gingerbeardman** [comment] 2024-04-12 19:48
BUT looking at this particular file, with more capable tools than I had a few years ago... and it seems to disagree with itself. 

My trusty Cot Editor shows it is encoded as `Shift JIS X0213` and the text seems to be Japanese but the meta says Korean. So Tcl doesn't do anything useful as it's not Korean.

**Comment by Sembiance** [comment] 2024-04-13 14:10
Thanks for the link to the script! Downloaded it and got it working on my side, looks useful! I'll still be using iconv for most things as I've added custom patches to it to support Atar ST, NEXTStep and RISCOS encodings. For KSC5601 though, I'll use your TCL script.

**Comment by gingerbeardman** [comment] 2024-04-13 19:59
Cool!

I'm still confused by what exactly this HTML file is. But it's not important!
